### ISSUE TITLE
olivetti-set-environment too expensive to call in post-command-hook

### ISSUE THREAD

**Issue by kqr** [rnkn/olivetti#28]
I don't know if this is due to some interaction effects with something else, and I'm not entirely sure how to check for that either, but my CPU profiler reported a lot of time being spent garbage collecting, and my memory profiler could confirm that

![image](https://user-images.githubusercontent.com/356598/56344269-4a03ff80-61bd-11e9-8267-ce08505c3299.png)

From having tried to written a similar mode to Olivetti before, I understand refreshing this after each command is a convenient option to ensure no edge case is missed, but with the input latency I get, I don't think it's worth it – regardless of how pretty my windows become with Olivetti turned on!

* Is there a quick way to check whether whatever processing we're about to do on the current window actually would change anything? And if not, just decline to do it?

* Would it perhaps be a solution to reset the environment in an idle timer instead?

* Or at least not run the processing if `this-command` is one of a predefined list of input commands, among others `'(self-insert-char backward-char forward-char delete-char delete-backward-char)` etc?

The help suggests for expensive post-command-hook functions to wrap the code in `(while-no-input (redisplay) CODE)` but that will terminate Olivetti processing midway through and leave buffers in invalid states.

**Comment by rnkn** [comment]
Try removing `window-configuration-change-hook` and see if you get better results. `post-command-hook` is actually not called as much as one might think.

**Comment by kqr** [comment]
Could you explain your reasoning for thinking that may be the culprit? The slowness was experienced while simply navigating left and right on a single line without triggering scrolling on any sort, so I have a hard time imagining that `window-configuration-change-hook` would be called. My suspicion of `post-command-hook` was further strengthened by the problem going away after I removed `olivetti-set-environment` from `post-command-hook`.

It might be because I have various other modes enabled, but for me, `post-command-hook` runs on pretty much every keypress. Among other things:

1. On arrow key navigation (`next-line`, `previous-line`, `evil-backward-char`, `evil-forward-char`),
2. On inserting keypresses in a buffer (`outshine-self-insert-command`), and
3. On inserting keypresses in the minibuffer (`self-insert-command`).

I'll give you that the amount of time I spend actively pressing keys is small in comparison to the time I spend looking at buffers, but using that to say "it's not called as much as one might think" seems like a mischaracterisation. During those short bursts of active typing are precisely the time I need insertion to be responsive!

**Comment by rnkn** [comment]
I know it seems counterintuitive; I got into a protracted argument with Eli about this but ended up eating humble pie because `window-configuration-change-hook` is called way more often than `post-command-hook`.

**Comment by rnkn** [comment]
Just checking you're using Emacs not Spacemacs right?

-- 
https://www.paulwrankin.com

**Comment by rnkn** [comment]
Might be able to get away with only `window-size-change-functions`, but that has broken compatibility in 27.x. I'm handing olivetti over to GNU ELPA so this should be fixed soon by people who know more about the display code than me.

**Comment by kqr** [comment]
I have no doubt that exchange happened, but I still don't know what you mean by "way more often".

I tried verifying my experience just now by adding a function to `window-configuration-change-hook` that incremented a number by one, and another function to `post-command-hook` that decremented the same variable by one. I then performed the operations I'm talking about (navigating around a buffer, inserting some text) for half a minute, and then when I displayed the value of the counter it was distinctly negative.

I'm not using Spacemacs (I still have nightmares from trying to wrap my head around configuring it!), but I do have `evil-mode` active.

**Comment by kqr** [comment]
Posting as a separate comment for emphasis:

I should state more clearly that this is not a general, constant problem, which makes it hard for me to isolate the issue. I'm currently running the default Olivetti hook set-up with no issues at all. This has yet only happened once, after Emacs had been running for quite some time. However, when it happened, it was very clear that the post-command-hook took way too long.

I'll try to remember to fill in more information if/when it happens again.

**Comment by rnkn** [comment]
Interesting. I tried a similar incrementing test and `window-configuration-change-hook` won. But that was maybe Emacs 25, and I suspect that work has been done to call that hook less and `window-size-change-functions` more.

I've had some feedback from Stefan about how best to get this working nicely so it should be better soon.

**Comment by rnkn** [comment]
I've switched back to `window-configuration-change-hook` and removed `post-command-hook`. Changes have been pushed to GitHub and GNU ELPA.

**Comment by kqr** [comment]
I have upgraded to the latest olivetti package now, and I'll try to take note of this happening again. Although due to the nature of the issue, it would take some time. I don't know if you want to close this issue and then I reopen it if it happens again, or however you want to handle it.

Thank you for maintaining such a great mode!

**Comment by rnkn** [comment]
Cool, thanks for checking it. I'll close now and if it you see further problems, can you report to <bug-gnu-emacs@gnu.org> (which will go to me).

I still need to push some more changes that should speed things up for Emacs 27. (I'm trying to keep support for Emacs 24 onwards.)
